### ISSUE TITLE
I cannot boot into this kernel from my Odroid U3

### ISSUE THREAD

**Issue by frol** [ztombol/odroid-tools#4]
1. I have fixed eMMC detection so uboot is flashed into a correct partition - #3
2. Modified `extlinux.conf` to point to `zImage-odroid` (I am not sure if extlinux is even used, but I thought it wouldn't hurt)
3. Added a symlink `/boot/zImage` to `zImage-odroid` (again, just in case)
4. Uncommented `root=/dev/mmcblk0p1` in `uEnv.txt`

My "alive" indicator just lights constantly instead of blinking and I cannot get any debug info out of my board because I only have HDMI TV, which doesn't receive anything from my board in such state.

Any help is appreciated.

**Comment by frol** [comment]
NOTE: I have built the latest 4.8.4 kernel.

**Comment by ztombol** [comment]
U-Boot is now [fused properly](https://github.com/ztombol/odroid-tools/pull/3) and there are [no more error messages](https://github.com/ztombol/odroid-tools/issues/2). For me, the kernel boots fine on both SD card and eMMC module.

Here is how boot looks like when looking at the _"alive"_ LED.
1. dim, solid - looking for the bootloader and loading it
2. normal, solid - booatloader loaded, looking for boot files and loading them
3. normal, blinking - kernel has been executed

I suspect you are stuck at 2, because you didn't specify the device tree file with the `fdtdir` directive.

```
default arch-tj

# Tobias Jakobi's upstream kernel with static MAC address.
label arch-tj
    linux ../zImage-odroid
    fdtdir ../dtbs-odroid
    append root=/dev/mmcblk1p1 rootwait rw console=ttySAC1,115200n8 smsc95xx.macaddr=02:de:ad:be:ef:ff
```

Note, when specifying the root file system, `/dev/mmcblk1` corresponds to the eMMC module, and `/dev/mmcblk0` corresponds to the SD card.

> Added a symlink /boot/zImage to zImage-odroid (again, just in case)

Not necessary. The `linux` directive in `extlinux.conf` is how U-Boot knows where to find the kernel image.

> Uncommented root=/dev/mmcblk0p1 in uEnv.txt

`extlinux.conf` takes precedence over `boot.scr` + `uEnv.txt`. This will become clear when I upload the documentation, which is almost finished.

**Comment by frol** [comment]
> Note, when specifying the root file system, `/dev/mmcblk1` corresponds to the eMMC module, and `/dev/mmcblk0` corresponds to the SD card.

It is true when both SD card and eMMC are inserted, but when I use only eMMC, it is assigned to `/dev/mmcblk0`.

> I suspect you are stuck at 2, because you didn't specify the device tree file with the `fdtdir` directive.

Aha, it seems like that. I will give it another try.

**Comment by frol** [comment]
Yey!!!

```
[u3 frol:~]$ uname -a
Linux u3 4.8.4-1-odroid #1 SMP PREEMPT Wed Oct 26 09:49:11 EEST 2016 armv7l GNU/Linux
```

Thank you!

**Comment by frol** [comment]
Hmm, I have tried to reboot and now I cannot boot again. It seems that something different is happening as I experience the following "alive" states:
1. dim, solid
2. normal, solid
3. normal, blinking 2-4 times
4. dead (sometimes ethernet lights are lighting solid, sometimes blinking is speeding up and only after a couple of more seconds the board goes dead)

**Comment by ztombol** [comment]
I had a similar issue while working on the U-Boot and Linux packages. I can't remember what caused it or how I resolved.

We seem to be seeing different device names, e.g. eMMC is always `mmcblk1` for me regardless whether the SD card is present. When the `root` filesystem is not found, the kernel should keep running, i.e. heartbeat should continue. So that shouldn't cause this issue, I think.

I suggest you start from scratch to elimninate as many factors as possible. Just in case, try only connecting either the eMMC module or the SD card, but not both.
1. **Reinstall U-Boot** - Use the `extlinux.conf` enabled package in this repo. The upstream package works too, but this one is easier to configure.
2. **Fuse boot media** - Thanks to you, both SD card and eMMC works too. Just pay attention to `root` filesystem configuration in _step 4_.
3. **Reinstall Linux kernel** - You'll see an example `extlinux.conf` that works with the U-Boot that you installed in _step 1_. Use this configuration in _step 4_. This only appears on installation. If you update to a new version of the same package, this message will not be shown.
4. **Configure U-Boot** - Use the example you saw during _step 3_. But make sure to properly set the `root` filesystem. For me, the SD card appears as `/dev/mmcblk0` and the eMMC module as `/dev/mmcblk1` even when only one of them is connected.
   
   For example to boot from eMMC:
   
   ```
   default arch-tj-emmc
   
   # Boot Tobias Jakobi's upstream kernel with static MAC address on an eMMC module.
   label arch-tj-emmc
       linux ../zImage-odroid
       fdtdir ../dtbs-odroid
       append root=/dev/mmcblk1p1 rootwait rw console=ttySAC1,115200n8 smsc95xx.macaddr=02:de:ad:be:ef:ff
   ```
   
   To boot from an SD card just set `root` to /dev/mmcblk**0**p1.

**Comment by frol** [comment]
Thank you for detailed instructions! I will give it a try once a have some spare time.

**Comment by ztombol** [comment]
@frol I think, the reason we saw different device names is because we used different kernels. I suspect you used 3.8 and I used 4.8. See below for details. This will be in the documentation, which should, hopefully, be ready by the end of the week.

**Linux 3.8**

The stock Arch Linux ARM kernel seems to assign names sequentially. First, the SD card (`mmc0`) is probed, if present it gets `mmcblk0` assigned to it. Then, the eMMC module (`mmc1`) is probed, if present it gets the next available device name, i.e. `mmcblk1` if the SD card is also present, `mmcblk0` otherwise. This behaviour seems to be consistent across reboots, but I would not rule out a possible race condition (e.g. how network interface names used to be assigned in older kernels).

| device | SD card only | Both | eMMC module only |
| --- | :-: | :-: | :-: |
| SD card | `mmcblk0` | `mmcblk0` | - |
| eMMC module | - | `mmcblk1` | `mmcblk0` |

**Linux 4.8**

Tobias Jakobi's near upstream kernel seems to use predictable device naming. While the SD card (`mmc0`) is probed first and the eMMC module (`mmc1`) last, the device names are consistent regardless which devices are present.

| device | always |
| --- | :-: |
| SD card | `mmcblk0` |
| eMMC module | `mmcblk1` |

**Comment by ztombol** [comment]
[U-Boot docs](https://github.com/ztombol/odroid-tools/blob/master/pkg/arch-arm/uboot-odroid/README.md) are up. This should clarify configuration. Linux docs should follow soon.

**Comment by ztombol** [comment]
[Linux docs](https://github.com/ztombol/odroid-tools/blob/master/pkg/arch-arm/linux-odroid/README.md) and a [U-Boot configuration example](https://github.com/ztombol/odroid-tools/blob/master/misc/u-boot/extlinux/extlinux.conf) are up too.

**Comment by frol** [comment]
This seems to be a bug in the Mali GPU support in the kernel rather than the packaging, so I close this bug and I will continue my experiments on the relevant thread: http://forum.odroid.com/viewtopic.php?f=55&t=3691&sid=2029ff48ffb1ad1653c9d5aa24830b52&start=300
